// Package hooks provides Git hook installation and management.
package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Type represents the kind of Git hook.
type Type string

const (
	PreCommit Type = "pre-commit"
	PrePush   Type = "pre-push"
)

// Options configures hook installation.
type Options struct {
	HookType string
	Force    bool
	Command  string // custom command to run in hook
}

// Install writes a Git hook script to .git/hooks/.
func Install(opts Options) error {
	hookType := Type(opts.HookType)
	if hookType != PreCommit && hookType != PrePush {
		return fmt.Errorf("unsupported hook type: %q (supported: pre-commit, pre-push)", opts.HookType)
	}

	gitDir, err := findGitDir()
	if err != nil {
		return err
	}

	hookPath := filepath.Join(gitDir, "hooks", string(hookType))

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil && !opts.Force {
		return fmt.Errorf("hook already exists at %s (use --force to overwrite)", hookPath)
	}

	cmd := opts.Command
	if cmd == "" {
		cmd = "envguard validate --strict"
	}

	script := generateHookScript(cmd)
	if err := os.WriteFile(hookPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write hook: %w", err)
	}

	return nil
}

// Uninstall removes a Git hook.
func Uninstall(hookType string) error {
	if Type(hookType) != PreCommit && Type(hookType) != PrePush {
		return fmt.Errorf("unsupported hook type: %q", hookType)
	}

	gitDir, err := findGitDir()
	if err != nil {
		return err
	}

	hookPath := filepath.Join(gitDir, "hooks", hookType)
	if err := os.Remove(hookPath); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("hook %s does not exist", hookType)
		}
		return fmt.Errorf("failed to remove hook: %w", err)
	}

	return nil
}

// Status checks if a hook is installed and returns its content.
func Status(hookType string) (bool, string, error) {
	if Type(hookType) != PreCommit && Type(hookType) != PrePush {
		return false, "", fmt.Errorf("unsupported hook type: %q", hookType)
	}

	gitDir, err := findGitDir()
	if err != nil {
		return false, "", err
	}

	hookPath := filepath.Join(gitDir, "hooks", hookType)
	data, err := os.ReadFile(hookPath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, "", nil
		}
		return false, "", err
	}

	content := string(data)
	isEnvGuard := strings.Contains(content, "envguard")
	return isEnvGuard, content, nil
}

func findGitDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		gitDir := filepath.Join(dir, ".git")
		info, err := os.Stat(gitDir)
		if err == nil && info.IsDir() {
			return gitDir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", fmt.Errorf("not inside a Git repository")
}

func generateHookScript(command string) string {
	return fmt.Sprintf(`#!/bin/sh
# Auto-generated by EnvGuard
# https://github.com/envguard/envguard

set -e

%s
`, command)
}
