// Package docs generates documentation from EnvGuard schemas.
package docs

import (
	"fmt"
	"sort"
	"strings"

	"github.com/envguard/envguard/internal/schema"
)

// Options configures documentation generation.
type Options struct {
	Format   string // markdown, html, json
	Template string // custom template path (optional)
	GroupBy  string // category, prefix, or ""
}

// Generate produces documentation from a schema.
func Generate(s *schema.Schema, opts Options) (string, error) {
	switch opts.Format {
	case "markdown", "md", "":
		return generateMarkdown(s, opts)
	case "html":
		return generateHTML(s, opts)
	case "json":
		return generateJSON(s, opts)
	default:
		return "", fmt.Errorf("unsupported format: %q", opts.Format)
	}
}

func generateMarkdown(s *schema.Schema, opts Options) (string, error) {
	var b strings.Builder

	b.WriteString("# Environment Variables\n\n")
	b.WriteString("> Auto-generated documentation from `envguard.yaml`\n\n")

	vars := sortVars(s)

	if opts.GroupBy == "prefix" {
		groups := groupByPrefix(vars)
		for _, group := range sortedGroupKeys(groups) {
			fmt.Fprintf(&b, "## %s\n\n", group)
			for _, name := range groups[group] {
				writeVarMarkdown(&b, name, s.Env[name])
			}
		}
	} else {
		b.WriteString("## Variables\n\n")
		for _, name := range vars {
			writeVarMarkdown(&b, name, s.Env[name])
		}
	}

	b.WriteString("---\n\n")
	b.WriteString("*Generated by [EnvGuard](https://github.com/envguard/envguard)*\n")

	return b.String(), nil
}

func writeVarMarkdown(b *strings.Builder, name string, v *schema.Variable) {
	fmt.Fprintf(b, "### `%s`\n\n", name)

	if v.Description != "" {
		fmt.Fprintf(b, "%s\n\n", v.Description)
	}

	b.WriteString("| Property | Value |\n")
	b.WriteString("|----------|-------|\n")
	fmt.Fprintf(b, "| **Type** | `%s` |\n", v.Type)

	if v.Required {
		b.WriteString("| **Required** | Yes |\n")
	}
	if v.Default != nil {
		fmt.Fprintf(b, "| **Default** | `%v` |\n", v.Default)
	}
	if len(v.Enum) > 0 {
		fmt.Fprintf(b, "| **Enum** | %v |\n", v.Enum)
	}
	if v.Format != "" {
		fmt.Fprintf(b, "| **Format** | `%s` |\n", v.Format)
	}
	if v.Pattern != "" {
		fmt.Fprintf(b, "| **Pattern** | `%s` |\n", v.Pattern)
	}
	if v.Min != nil {
		fmt.Fprintf(b, "| **Min** | `%v` |\n", v.Min)
	}
	if v.Max != nil {
		fmt.Fprintf(b, "| **Max** | `%v` |\n", v.Max)
	}
	if v.Deprecated != "" {
		fmt.Fprintf(b, "| **Deprecated** | %s |\n", v.Deprecated)
	}
	if v.Sensitive {
		b.WriteString("| **Sensitive** | Yes |\n")
	}

	b.WriteString("\n")
}

func generateHTML(s *schema.Schema, opts Options) (string, error) {
	md, err := generateMarkdown(s, opts)
	if err != nil {
		return "", err
	}
	// Very basic HTML wrapper
	html := `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Environment Variables</title><style>
body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:0 20px}
table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}
th{background:#f5f5f5}code{background:#f4f4f4;padding:2px 6px;border-radius:3px}
h2{border-bottom:2px solid #eee;padding-bottom:8px}
</style></head>
<body>`
	// Very naive markdown-to-html conversion
	lines := strings.Split(md, "\n")
	var out strings.Builder
	inTable := false
	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, "# "):
			fmt.Fprintf(&out, "<h1>%s</h1>\n", strings.TrimPrefix(line, "# "))
		case strings.HasPrefix(line, "## "):
			fmt.Fprintf(&out, "<h2>%s</h2>\n", strings.TrimPrefix(line, "## "))
		case strings.HasPrefix(line, "### "):
			fmt.Fprintf(&out, "<h3>%s</h3>\n", strings.TrimPrefix(line, "### "))
		case strings.HasPrefix(line, "| ") && strings.Contains(line, " | "):
			if !inTable {
				out.WriteString("<table>\n")
				inTable = true
			}
			if strings.Contains(line, "---|") {
				continue
			}
			parts := strings.Split(line, "|")
			out.WriteString("<tr>")
			for i, p := range parts {
				if i == 0 || i == len(parts)-1 {
					continue
				}
				cell := strings.TrimSpace(p)
				cell = strings.ReplaceAll(cell, "`", "<code>")
				if strings.Count(cell, "<code>")%2 == 1 {
					cell += "</code>"
				}
				if i == 1 {
					fmt.Fprintf(&out, "<th>%s</th>", cell)
				} else {
					fmt.Fprintf(&out, "<td>%s</td>", cell)
				}
			}
			out.WriteString("</tr>\n")
		case line == "":
			if inTable {
				out.WriteString("</table>\n")
				inTable = false
			}
			out.WriteString("<p>\n")
		default:
			fmt.Fprintf(&out, "<p>%s</p>\n", line)
		}
	}
	if inTable {
		out.WriteString("</table>\n")
	}
	return html + out.String() + "</body></html>", nil
}

func generateJSON(s *schema.Schema, opts Options) (string, error) {
	var b strings.Builder
	b.WriteString("{\n")
	b.WriteString(`  "version": "` + s.Version + `",` + "\n")
	b.WriteString(`  "variables": {` + "\n")
	vars := sortVars(s)
	for i, name := range vars {
		v := s.Env[name]
		fmt.Fprintf(&b, `    "%s": {`+"\n", name)
		fmt.Fprintf(&b, `      "type": "%s"`+"\n", v.Type)
		if v.Description != "" {
			fmt.Fprintf(&b, `      ,"description": "%s"`+"\n", v.Description)
		}
		if v.Required {
			b.WriteString(`      ,"required": true` + "\n")
		}
		if v.Default != nil {
			fmt.Fprintf(&b, `      ,"default": "%v"`+"\n", v.Default)
		}
		b.WriteString("    }")
		if i < len(vars)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func sortVars(s *schema.Schema) []string {
	var names []string
	for name := range s.Env {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func groupByPrefix(vars []string) map[string][]string {
	groups := make(map[string][]string)
	for _, v := range vars {
		prefix := "Other"
		if idx := strings.Index(v, "_"); idx > 0 {
			prefix = v[:idx]
		}
		groups[prefix] = append(groups[prefix], v)
	}
	return groups
}

func sortedGroupKeys(groups map[string][]string) []string {
	var keys []string
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
