package sync

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/envguard/envguard/internal/schema"
)

func TestParseEnvFileNotExist(t *testing.T) {
	entries, lookup, err := parseEnvFile("/nonexistent/.env")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(entries) != 0 {
		t.Errorf("expected 0 entries, got %d", len(entries))
	}
	if len(lookup) != 0 {
		t.Errorf("expected empty lookup, got %d", len(lookup))
	}
}

func TestParseEnvFileLinesWithoutEquals(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, ".env")
	content := "KEY=value\nINVALID_LINE\n# comment\n\n"
	os.WriteFile(path, []byte(content), 0644)

	entries, lookup, err := parseEnvFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(entries) != 4 {
		t.Errorf("expected 4 entries, got %d", len(entries))
	}
	if lookup["KEY"].Value != "value" {
		t.Errorf("expected KEY=value, got %q", lookup["KEY"].Value)
	}
	// INVALID_LINE should be in entries but not in lookup
	_, exists := lookup["INVALID_LINE"]
	if exists {
		t.Error("INVALID_LINE should not be in lookup")
	}
}

func TestRunNoDriftWithSchema(t *testing.T) {
	tmpDir := t.TempDir()

	envPath := filepath.Join(tmpDir, ".env")
	os.WriteFile(envPath, []byte("API_KEY=secret123\n"), 0644)

	examplePath := filepath.Join(tmpDir, ".env.example")
	os.WriteFile(examplePath, []byte("API_KEY=***\n"), 0644)

	schemaPath := filepath.Join(tmpDir, "envguard.yaml")
	os.WriteFile(schemaPath, []byte(`
version: "1.0"
env:
  API_KEY:
    type: string
    sensitive: true
`), 0644)

	result, err := Run(Options{
		EnvPath:     envPath,
		ExamplePath: examplePath,
		SchemaPath:  schemaPath,
		Check:       true,
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	// The example content differs from what would be generated, so there IS drift
	if !result.WouldWrite {
		t.Log("Note: WouldWrite is false - example matches expected output")
	}
}

func TestRunDriftDetectionNoChanges(t *testing.T) {
	tmpDir := t.TempDir()

	envPath := filepath.Join(tmpDir, ".env")
	os.WriteFile(envPath, []byte("API_KEY=secret123\n"), 0644)

	examplePath := filepath.Join(tmpDir, ".env.example")
	// Write the exact same content that generateExample would produce
	os.WriteFile(examplePath, []byte("# Auto-generated by EnvGuard sync\n# Copy this file to .env and fill in the values\n\nAPI_KEY=secret123\n"), 0644)

	result, err := Run(Options{
		EnvPath:     envPath,
		ExamplePath: examplePath,
		SchemaPath:  "",
		Check:       true,
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	if result.WouldWrite {
		t.Error("expected WouldWrite to be false when content matches")
	}
}

func TestRunSensitiveMissingInExample(t *testing.T) {
	tmpDir := t.TempDir()

	envPath := filepath.Join(tmpDir, ".env")
	os.WriteFile(envPath, []byte("API_KEY=secret123\n"), 0644)

	examplePath := filepath.Join(tmpDir, ".env.example")
	os.WriteFile(examplePath, []byte(""), 0644)

	schemaPath := filepath.Join(tmpDir, "envguard.yaml")
	os.WriteFile(schemaPath, []byte(`
version: "1.0"
env:
  API_KEY:
    type: string
    sensitive: true
`), 0644)

	result, err := Run(Options{
		EnvPath:     envPath,
		ExamplePath: examplePath,
		SchemaPath:  schemaPath,
		Check:       true,
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	if !result.WouldWrite {
		t.Error("expected WouldWrite to be true")
	}

	found := false
	for _, diff := range result.Diffs {
		if diff.Key == "API_KEY" && diff.EnvVal == "***" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected API_KEY to be masked in diffs, got: %+v", result.Diffs)
	}
}

func TestRunSchemaParseError(t *testing.T) {
	tmpDir := t.TempDir()

	envPath := filepath.Join(tmpDir, ".env")
	os.WriteFile(envPath, []byte("KEY=value\n"), 0644)

	examplePath := filepath.Join(tmpDir, ".env.example")
	os.WriteFile(examplePath, []byte("KEY=\n"), 0644)

	schemaPath := filepath.Join(tmpDir, "envguard.yaml")
	os.WriteFile(schemaPath, []byte("invalid yaml ::: ["), 0644)

	_, err := Run(Options{
		EnvPath:     envPath,
		ExamplePath: examplePath,
		SchemaPath:  schemaPath,
	})
	if err == nil {
		t.Error("expected error for invalid schema")
	}
}

func TestGenerateExampleEmptyEnv(t *testing.T) {
	entries := []envEntry{}
	lookup := make(map[string]envEntry)
	exampleLookup := make(map[string]envEntry)
	sensitiveSet := make(map[string]bool)

	result := generateExample(entries, []envEntry{}, lookup, exampleLookup, sensitiveSet, nil)
	if result == "" {
		t.Error("expected non-empty result")
	}
	if !strings.Contains(result, "Auto-generated by EnvGuard sync") {
		t.Error("expected header comment")
	}
}

func TestGenerateExampleConsecutiveBlanks(t *testing.T) {
	entries := []envEntry{
		{Key: "KEY1", Value: "val1", Raw: "KEY1=val1"},
		{Key: "", IsBlank: true, Raw: ""},
		{Key: "", IsBlank: true, Raw: ""},
		{Key: "KEY2", Value: "val2", Raw: "KEY2=val2"},
	}
	lookup := map[string]envEntry{
		"KEY1": {Key: "KEY1", Value: "val1"},
		"KEY2": {Key: "KEY2", Value: "val2"},
	}
	exampleLookup := make(map[string]envEntry)
	sensitiveSet := make(map[string]bool)

	result := generateExample(entries, []envEntry{}, lookup, exampleLookup, sensitiveSet, nil)
	// Should contain both keys (suggestPlaceholder may transform values)
	if !strings.Contains(result, "KEY1=") {
		t.Error("expected KEY1 in output")
	}
	if !strings.Contains(result, "KEY2=") {
		t.Error("expected KEY2 in output")
	}
	// Count blank lines - should not have consecutive blanks
	// (exclude trailing empty line from final "\n")
	lines := strings.Split(strings.TrimSuffix(result, "\n"), "\n")
	blankCount := 0
	for _, line := range lines {
		if line == "" {
			blankCount++
		}
	}
	// Header has one blank line after comments, plus one between KEY1 and KEY2
	if blankCount > 2 {
		t.Errorf("expected at most 2 blank lines, got %d", blankCount)
	}
}

func TestSuggestPlaceholderWithSchemaDefault(t *testing.T) {
	sch := &schema.Schema{
		Version: "1.0",
		Env: map[string]*schema.Variable{
			"PORT": {Type: schema.TypeInteger, Default: 3000},
		},
	}

	got := suggestPlaceholder("PORT", "", sch)
	if got != "3000" {
		t.Errorf("expected '3000', got %q", got)
	}
}

func TestSuggestPlaceholderEmptyNoSchema(t *testing.T) {
	got := suggestPlaceholder("UNKNOWN", "", nil)
	if got != "" {
		t.Errorf("expected empty string, got %q", got)
	}
}

func TestSuggestPlaceholderPortWithValue(t *testing.T) {
	got := suggestPlaceholder("SERVER_PORT", "8080", nil)
	if got != "8080" {
		t.Errorf("expected '8080', got %q", got)
	}
}

func TestSuggestPlaceholderDatabaseURL(t *testing.T) {
	got := suggestPlaceholder("DATABASE_URL", "postgres://localhost", nil)
	want := "postgresql://user:password@localhost:5432/dbname"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestSuggestPlaceholderRedisURL(t *testing.T) {
	got := suggestPlaceholder("REDIS_URL", "redis://localhost", nil)
	want := "redis://localhost:6379"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestSuggestPlaceholderKey(t *testing.T) {
	got := suggestPlaceholder("API_KEY", "abc", nil)
	want := "your-api-key-here"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestSuggestPlaceholderPort(t *testing.T) {
	got := suggestPlaceholder("PORT", "8080", nil)
	if got != "8080" {
		t.Errorf("expected '8080', got %q", got)
	}
}

func TestSuggestPlaceholderURL(t *testing.T) {
	got := suggestPlaceholder("WEBSITE_URL", "https://example.com", nil)
	if got != "https://example.com" {
		t.Errorf("expected 'https://example.com', got %q", got)
	}
}

func TestParseEnvWrapper(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, ".env")
	os.WriteFile(path, []byte("KEY=value\n"), 0644)

	vars, err := ParseEnv(path)
	if err != nil {
		t.Fatalf("ParseEnv failed: %v", err)
	}
	if vars["KEY"] != "value" {
		t.Errorf("expected KEY=value, got %q", vars["KEY"])
	}
}

func TestRunAddMissingEnvNotExist(t *testing.T) {
	tmpDir := t.TempDir()

	envPath := filepath.Join(tmpDir, ".env")
	os.WriteFile(envPath, []byte("API_KEY=secret123\n"), 0644)

	examplePath := filepath.Join(tmpDir, ".env.example")
	os.WriteFile(examplePath, []byte("API_KEY=\nEXTRA_VAR=hello\n"), 0644)

	result, err := Run(Options{
		EnvPath:     envPath,
		ExamplePath: examplePath,
		Check:       false,
		AddMissing:  true,
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	_ = result

	envContent, _ := os.ReadFile(envPath)
	if !strings.Contains(string(envContent), "EXTRA_VAR=") {
		t.Errorf("expected .env to contain EXTRA_VAR after --add-missing, got:\n%s", string(envContent))
	}
}

func TestGenerateExampleSchemaVarsOnly(t *testing.T) {
	// When envEntries is empty but schema has vars
	entries := []envEntry{}
	lookup := make(map[string]envEntry)
	exampleLookup := make(map[string]envEntry)
	sensitiveSet := map[string]bool{"SECRET": true}
	sch := &schema.Schema{
		Version: "1.0",
		Env: map[string]*schema.Variable{
			"SECRET": {Type: schema.TypeString, Sensitive: true},
			"NORMAL": {Type: schema.TypeString},
		},
	}

	result := generateExample(entries, nil, lookup, exampleLookup, sensitiveSet, sch)
	if !strings.Contains(result, "SECRET=***") {
		t.Error("expected SECRET to be masked")
	}
	if !strings.Contains(result, "NORMAL=") {
		t.Error("expected NORMAL in output")
	}
}
